//! Raw FFI bindings to librknnrt.
//!
//! Pre-generated by bindgen 0.71 from
//! `vendor/rknn/include/rknn_custom_op.h` and checked in as
//! `vendor/rknn/rknn_bindings.rs`. Vendoring the bindings avoids requiring
//! libclang on aarch64 build hosts (e.g. RK3588 itself); regenerate with
//! `tools/rknn-convert/regen-bindings.sh` if the header changes.

#![cfg(all(target_arch = "aarch64", feature = "rknpu"))]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(clippy::all)]

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/vendor/rknn/rknn_bindings.rs"
));
